add suppression of FP for  postgis-jdbc jar
dependency-check/DependencyCheck pull request #1661
Opened 2019-01-03 09:03 UTC by mprins

## Fixes Issue #1660 
close #1660

## Description of Change
adds suppression of false identification of the postgis jdbc driver, 
Alternatively you may just use the cve's listed in the issue.

## Have test cases been added to cover the new functionality?
no

2019-01-03 11:50 UTC, jeremylong requested changes

2019-01-03 11:50 UTC, jeremylong commented on core/src/main/resources/dependencycheck-base-suppression.xml
> +        <cpe>cpe:/a:postgresql:postgresql</cpe>
This appears to be missing the GAV element?
```suggestion
        <gav regex="true">^net\.postgis:postgis-jdbc:.*$</gav>
        <cpe>cpe:/a:postgresql:postgresql</cpe>
```

2019-01-23 12:13 UTC, jeremylong commented
There has been a long debate around suppressing the CPE for the server vs. the JDBC driver - the concern is by suppressing the full CPE this could mask vulnerabilities identified in the driver. As such, we created sections in the suppression file to suppress individual CVEs for the server: https://github.com/jeremylong/DependencyCheck/blob/673885b9c2f4d108ad28cd9832983ab5a791d348/core/src/main/resources/dependencycheck-base-suppression.xml#L2205-L2211

2019-01-24 08:12 UTC, mprins commented
that's fine too, I'll close this then

2019-01-24 08:12 UTC, closed without merging