suppression rule for #1229
dependency-check/DependencyCheck pull request #1672
Opened 2019-01-08 22:36 UTC by stepio

## Fixes Issue #1229

## Description of Change

Ignore false positive for `org.slf4j:slf4j-api:*`.

## Have test cases been added to cover the new functionality?

*no*

2019-01-15 16:56 UTC, stepio commented
Ping @jeremylong.

Hello, any news?

2019-01-23 12:09 UTC, jeremylong requested changes
The suppression should be specific to the CVE in this case.

2019-01-23 12:09 UTC, jeremylong commented on core/src/main/resources/dependencycheck-base-suppression.xml
> +        <cpe>cpe:/a:slf4j:slf4j</cpe>
This really should be a very specific suppression otherwise we risk masking CVEs for slf4j.
```suggestion
        <cve>CVE-2018-8088</cve>
```

2019-01-23 15:54 UTC, stepio commented on core/src/main/resources/dependencycheck-base-suppression.xml
> +        <cpe>cpe:/a:slf4j:slf4j</cpe>
I started with suppressing just `slf4j-api` as a constant value. But then I checked other comments and the original CVE and understood that although issue was raised only for `slf4j-ext`, most of the slf4j libs are detected.

So I decided that adding a single rule could be an improvement. But... you're the boss - `slf4j-api` is more than enough for my case.

I'll push the update today, thanks.

2019-01-23 17:53 UTC, stepio commented on core/src/main/resources/dependencycheck-base-suppression.xml
> +        <cpe>cpe:/a:slf4j:slf4j</cpe>
Sorry, ignore my previous note, you're completely right.

2019-01-24 01:07 UTC, merged