Add Pipfile Analyzer
dependency-check/DependencyCheck pull request #2877
Opened 2020-10-09 11:08 UTC by fcano

#  Description of Change

Add a basic Pipfile Analyzer.

## Have test cases been added to cover the new functionality?

yes

2020-10-10 10:30 UTC, jeremylong requested changes
Thank you for such a complete PR! Just one minor suggestions - unless you can think of any other way to obtain vendor information from pip...

2020-10-10 10:30 UTC, jeremylong commented on core/src/main/java/org/owasp/dependencycheck/analyzer/PipfileAnalyzer.java
> +                    d.addEvidence(EvidenceType.PRODUCT, REQUIREMENTS, "product", identifiedPackage, Confidence.HIGHEST);
Unfortunately - there is a requirement to have at least some vendor evidence. In a case like this where we don't have a vendor the recommendation is to just put the product name in as the vendor.

```suggestion
                    d.addEvidence(EvidenceType.VENDOR, REQUIREMENTS, "vendor", identifiedPackage, Confidence.HIGHEST);
                    d.addEvidence(EvidenceType.PRODUCT, REQUIREMENTS, "product", identifiedPackage, Confidence.HIGHEST);
```

2020-10-11 10:12 UTC, fcano commented
@jeremylong do you know why the test failed? Looking into the logs it does not seem a problem with the commit.

2020-10-11 11:54 UTC, jeremylong commented
Apparently I broke the build.  If you `git rebase main` this should resolve itself.   Otherwise I know this builds and is correct - I can just merge...

2020-10-11 17:25 UTC, fcano commented
The idea is to 'git rebase main' the branch 'add-pipfile-support' and drop the last commi (ab94853)?

2020-10-11 18:43 UTC, fcano commented
I think I did it. Now, the PR does not have an evidence for the VENDOR. Is it mandatory? I don't see that line in the PipAnalyzer for example. It only has these two lines:

https://github.com/jeremylong/DependencyCheck/pull/2526/files#diff-13b45a953258e6e7d4327bc57ef26169R163-R164

2020-10-11 20:43 UTC, jeremylong commented on core/src/main/java/org/owasp/dependencycheck/analyzer/PipfileAnalyzer.java
> +                    d.addEvidence(EvidenceType.PRODUCT, REQUIREMENTS, "product", identifiedPackage, Confidence.HIGHEST);
```suggestion
                    d.addEvidence(EvidenceType.VENDOR, REQUIREMENTS, "vendor", identifiedPackage, Confidence.HIGHEST);
                    d.addEvidence(EvidenceType.PRODUCT, REQUIREMENTS, "product", identifiedPackage, Confidence.HIGHEST);
```

2020-10-11 20:44 UTC, jeremylong approved these changes

2020-10-11 20:45 UTC, jeremylong commented
I just put the line adding the vendor evidence back. As to what happened - you likely accepted my change request in the github UI and did not pull the update back in before rebasing.

Seriously - that you for such a complete PR!

2020-10-12 16:52 UTC, fcano commented
I'm sorry because I don't have a lot of experience with git and I got lost with the rebase. Now I see your commit in the pull request and the tests passing. Is everything ok now? Is there anything else that I have to do?

2020-10-12 18:58 UTC, jeremylong commented
Yup - everything is good.  Thanks for the PR!

2020-10-12 18:58 UTC, merged