False positive as per #2821
dependency-check/DependencyCheck pull request #2887
Opened 2020-10-12 15:19 UTC by stephenbarry-transunion

## Fixes Issue #
Fixes #2821 

## Description of Change
Suppress false positive in base

## Have test cases been added to cover the new functionality?

N/A

2020-10-12 19:03 UTC, jeremylong requested changes
Did you test the suppression rule? The regex on the packageUrl doesn't look right to me - see my suggestion.

2020-10-12 19:03 UTC, jeremylong commented on core/src/main/resources/dependencycheck-base-suppression.xml
> +        <packageUrl regex="true">^pkg:(generic|nuget)/Microsoft\.VisualStudio\.Web\.CodeGenerat...\.*$</packageUrl>
```suggestion
        <packageUrl regex="true">^pkg:(generic|nuget)/Microsoft\.VisualStudio\.Web\.CodeGenerat.*$</packageUrl>
```

2020-10-13 16:14 UTC, stephenbarry-transunion commented on core/src/main/resources/dependencycheck-base-suppression.xml
> +        <packageUrl regex="true">^pkg:(generic|nuget)/Microsoft\.VisualStudio\.Web\.CodeGenerat...\.*$</packageUrl>
Hi Jeremy, I had not, but I have now and you're correct that my initial regex wasn't working as expected. Your suggestion works as expected, see the attached test report.

![image](https://user-images.githubusercontent.com/50362641/95887251-8515cd80-0d77-11eb-9024-fce0046b8c01.png)

2020-10-14 10:09 UTC, jeremylong approved these changes

2020-10-14 10:10 UTC, merged

2020-10-14 10:10 UTC, jeremylong commented
Thanks for the PR