Set length of versionEndExcluding, versionEndIncluding, versionStartExcluding and versionStartIncluding to 60
dependency-check/DependencyCheck pull request #3488
Opened 2021-07-01 12:28 UTC by Skyball2000

## Fixes Issue #
See issue https://github.com/jeremylong/DependencyCheck/issues/3483
closes #3483 

## Description of Change

Set length of columns `versionEndExcluding`, `versionEndIncluding`, `versionStartExcluding` and `versionStartIncluding` to `60`
Set schema version to `5.2`

## Have test cases been added to cover the new functionality?

no

2021-07-02 13:11 UTC, jeremylong requested changes

2021-07-02 13:11 UTC, jeremylong commented on core/src/main/resources/data/upgrade_5.0.sql
> +UPDATE Properties SET value='5.2' WHERE ID='version';
The upgrade_5.0.sql should not be modified. Instead, a new file `upgrade_5.1.sql` should be created that contains the upgrade steps for a schema to go from 5.1 to 5.2.

For this PR we should revert the change:
```suggestion
UPDATE Properties SET value='5.1' WHERE ID='version';
```

Then create the new file with something like (note, I haven't tested this SQL yet): 
```sql
ALTER TABLE software ALTER COLUMN versionEndExcluding SET DATA TYPE VARCHAR(60);
ALTER TABLE software ALTER COLUMN versionEndIncluding SET DATA TYPE VARCHAR(60);
ALTER TABLE software ALTER COLUMN versionStartExcluding SET DATA TYPE VARCHAR(60);
ALTER TABLE software ALTER COLUMN versionStartIncluding SET DATA TYPE VARCHAR(60);

UPDATE Properties SET value='5.2' WHERE ID='version'; 
```

2021-07-02 17:31 UTC, Skyball2000 commented on core/src/main/resources/data/upgrade_5.0.sql
> +UPDATE Properties SET value='5.2' WHERE ID='version';
That makes sense. I reverted the change to `upgrade_5.0.sql` and created the new file `upgrade_5.1.sql` according to your code.

2021-07-02 17:36 UTC, Skyball2000 commented
Should I also revert the other file change then? I previously also changed `core/src/main/resources/data/initialize.sql` to a lenght of `60`:
```
CREATE TABLE software (cveid INT, cpeEntryId INT, versionEndExcluding VARCHAR(60), versionEndIncluding VARCHAR(60),
versionStartExcluding VARCHAR(60), versionStartIncluding VARCHAR(60), vulnerable BOOLEAN
```
But if the table gets upgraded by the sql instructions in `upgrade_5.1.sql` later on, shouldn't this be `50`?

2021-07-07 11:22 UTC, jeremylong approved these changes
Thanks for updating the PR! This will be merged before the next release.

2021-07-19 11:25 UTC, jeremylong approved these changes

2021-07-20 11:05 UTC, merged