Add --nodePackageSkipDevDependencies CLI option
dependency-check/DependencyCheck pull request #3507
Opened 2021-07-12 18:31 UTC by Aeyaa

Add an option '--nodePackageSkipDevDependencies' to skip dev
dependencies in the Node Package analyzer.

## Fixes Issue #

#3506 

## Description of Change

Add an option '--nodePackageSkipDevDependencies' to skip dev
dependencies in the Node Package analyzer.

*Please add a description of the proposed change*

When analyzing the the package-lock.json in the Node Package analyzer, if the dependency has the field `{..., "dev": true} ` and '--nodePackageSkipDevDependencies' option was used, then skip the analysis for this dependency. 

## Have test cases been added to cover the new functionality?

no

2021-07-13 11:24 UTC, jeremylong requested changes
While I'm okay adding this for now - the longer term solution is going to be folding the node package analyzer and node audit analyzer into a single analyzer. Just spotted one possible issue with the PR though.

2021-07-13 11:24 UTC, jeremylong commented on core/src/main/java/org/owasp/dependencycheck/analyzer/NodePackageAnalyzer.java
> +                    return;
Shouldn't this be continue instead of return?

```suggestion
                    continue;
```

2021-07-13 16:22 UTC, Aeyaa commented on core/src/main/java/org/owasp/dependencycheck/analyzer/NodePackageAnalyzer.java
> +                    return;
You are absolutely correct, it should be continue 🙂

2021-07-29 11:13 UTC, jeremylong approved these changes

2021-07-29 12:21 UTC, jeremylong commented
This was merged manually.

2021-07-29 12:21 UTC, closed without merging