Fix ConcurrentModificationException
dependency-check/DependencyCheck pull request #3561
Opened 2021-08-04 12:34 UTC by jeremylong

Initial fix for ConcurrentModificationException introduced by #3466.

2021-08-04 12:35 UTC, jeremylong commented on core/src/main/java/org/owasp/dependencycheck/dependency/Dependency.java
> +     * Clears the {@link #relatedDependencies}.      *
```suggestion
     * Clears the {@link #relatedDependencies}.
```

2021-08-04 13:07 UTC, aikebah commented
Same fix is needed for DependencyMergingAnalyzer at lines [147-149](https://github.com/jeremylong/DependencyCheck/blob/6832c6434cf60df146f0ff6704c4c082cee13519/core/src/main/java/org/owasp/dependencycheck/analyzer/DependencyMergingAnalyzer.java#L147-L149).

2021-08-04 13:11 UTC, aikebah commented
Sorry... overlooked that file in the changelog... It's already in there. So that leaves only FalsePostiveAnalyzer.removeBadMatches which removes items from vulnerableSoftwareIdentifiers while while iterating over them

```
exception: java.util.ConcurrentModificationException

java.util.TreeMap$PrivateEntryIterator.nextEntry(TreeMap.java:1211)
java.util.TreeMap$KeyIterator.next(TreeMap.java:1265)
java.util.Collections$UnmodifiableCollection$1.next(Collections.java:1044)
org.owasp.dependencycheck.analyzer.FalsePositiveAnalyzer.removeBadMatches(FalsePositiveAnalyzer.java:281)
```

2021-08-04 13:33 UTC, aikebah requested changes
These look good to me, and also get rid of a [potentially dangerous state-modifying peek](https://4comprehension.com/idiomatic-peeking/) that was signalled by SonarLint.

When a [FalsePositiveAnalyzer#removeBadMatches](https://github.com/jeremylong/DependencyCheck/blob/6832c6434cf60df146f0ff6704c4c082cee13519/core/src/main/java/org/owasp/dependencycheck/analyzer/FalsePositiveAnalyzer.java#L281) fix gets added as far as I can see no further ConcurrentModifcationExceptions should happen (all other uses of the set-getters appear to be read-only usage, already employ a defensive copy or imlement a 'gather' phase followed by an 'update' phase in the code)

2021-08-05 11:14 UTC, aikebah approved these changes, later dismissed
LGTM

2021-08-05 11:21 UTC, jeremylong commented on core/src/main/java/org/owasp/dependencycheck/analyzer/FalsePositiveAnalyzer.java
> +        Set<Identifier> toRemove = new HashSet<>();
```suggestion
        final Set<Identifier> toRemove = new HashSet<>();
```

2021-08-05 11:57 UTC, merged