support partial fingerprints for sarif reports
dependency-check/DependencyCheck pull request #4200
Opened 2022-03-14 16:53 UTC by timdodd

## Fixes Issue #

N/A

## Description of Change

This change is to support [partial fingerprints](https://docs.oasis-open.org/sarif/sarif/v2.0/csprd02/sarif-v2.0-csprd02.html#_Toc10127846) for the sarif report. The partial fingerprint is generated based on the vulnerability name (cve or cwe). 

This change was made to support [github code scanning](https://docs.github.com/en/code-security/code-scanning/integrating-with-code-scanning/sarif-support-for-code-scanning) and prevents duplicate alerts across branches.

> If you upload a SARIF file without fingerprint data using the /code-scanning/sarifs API endpoint, the code scanning alerts will be processed and displayed, but users may see duplicate alerts. To avoid seeing duplicate alerts, you should calculate fingerprint data and populate the partialFingerprints property before you upload the SARIF file.  

## Have test cases been added to cover the new functionality?

Sarif report testing has been added to ReportGeneratorIT; however, the test doesn't inspect the contents.

2022-03-18 12:12 UTC, jeremylong requested changes
Thanks for the PR - however, would you mind updating the PR to use the existing wrapper to generate hashes?

2022-03-18 12:12 UTC, jeremylong commented on core/src/main/java/org/owasp/dependencycheck/reporting/ReportGenerator.java
> +        ctxt.put("hash", new HashTool());
Use existing objects:

```suggestion
        ctxt.put("hash", org.owasp.dependencycheck.utils.Checksum.class);
```

2022-03-18 12:12 UTC, jeremylong commented on core/src/main/resources/templates/sarifReport.vsl
> +            "vulnerabilityHash": "$hash.md5Hex($vuln.name)"
Use existing methods:
```suggestion
            "vulnerabilityHash": "$hash. getMD5Checksum($vuln.name)"
```

2022-03-18 12:12 UTC, jeremylong commented on core/src/main/java/org/owasp/dependencycheck/reporting/HashTool.java
> +public class HashTool {
This wrapper is duplicative and should be removed from the PR. See https://github.com/jeremylong/DependencyCheck/blob/3d097c4838d21d861753a0ea77cde92af19fac40/utils/src/main/java/org/owasp/dependencycheck/utils/Checksum.java#L188-L190

2022-03-18 15:00 UTC, timdodd commented
Thanks for the comments and review! The PR has been updated with the requested changes.

2022-03-20 11:08 UTC, jeremylong approved these changes

2022-03-20 11:13 UTC, merged