Update pom.xml
dependency-check/DependencyCheck pull request #4281
Opened 2022-03-28 16:09 UTC by Grimoren

## Fixes Issue #
4280

## Description of Change
use valid jackson version
*Please add a description of the proposed change*

## Have test cases been added to cover the new functionality?
no

2022-03-28 16:24 UTC, Grimoren commented
It seems that 2.13.2.1 is valid for most jackson with exception to jackson-bom:
https://mvnrepository.com/artifact/com.fasterxml.jackson/jackson-bom/2.13.2.20220324

2022-03-28 16:32 UTC, Janpopan commented
```xml
<dependency>
    <groupId>com.fasterxml.jackson</groupId>
    <artifactId>jackson-bom</artifactId>
    <version>2.13.2.20220324</version>
    <type>pom</type>
</dependency>
```

2022-03-28 19:27 UTC, mprins commented on pom.xml
> +            </dependency>
to use a BOM in maven the `<scope>import</scope>` should be used

2022-03-29 04:17 UTC, juergenzimmermann requested changes
Meanwhile there is Jackson BOM `2.13.2.20220328`. See https://github.com/FasterXML/jackson-databind/issues/3428

2022-03-29 07:23 UTC, chadlwilson commented
According to https://github.com/FasterXML/jackson-databind/issues/3428#issuecomment-1081330160 it seems the right way forward here is to roll forward to `jackson.version` of `2.13.2.2` which corrects the Gradle metadata causing problems for Gradle users (and dependency-check-gradle).

(Or move to a BOM-based approach entirely which would be more work, and involve removing the specific versions for `jackson-databind`)

2022-03-29 09:30 UTC, philsegal commented on pom.xml
> +            </dependency>
try using Jackson version `2.13.2.2` instead?

2022-03-29 10:30 UTC, jeremylong commented
superseded by #4285

2022-03-29 10:30 UTC, closed without merging