Log when non-base suppressions rules are unused
dependency-check/DependencyCheck pull request #4709
Opened 2022-07-27 11:08 UTC by jeremylong

Supersedes #4687 

Fixes https://github.com/jeremylong/DependencyCheck/issues/4685

This might be useful to some - a log message has been added when a non-base suppression rule was not used.

2022-08-01 18:55 UTC, aikebah commented
Need to get my head around the why, but it appears to break the suppression of https://github.com/jeremylong/DependencyCheck/commit/83e0f647912716a71b58306a7368809cb967d796

causing integration-test 629 to fail as cbor gets bundled with ion as the CVE is no longer suppressed for ion

2022-08-02 09:49 UTC, jeremylong commented
I've been off and on looking at this as time permits - I haven't been able to figure out why this PR breaks 629 and does not suppress the CVE for ion...

2022-08-10 17:15 UTC, aikebah commented
> I've been off and on looking at this as time permits - I haven't been able to figure out why this PR breaks 629 and does not suppress the CVE for ion...

Added a few pieces of targeted debugging and finally got around the root-cause... the singleton is reused in CPESuppressionAnalyzer and VulnerabilitySuppressionAnalyzer, so rather that 55 CVE suppressions + 3 vulnerabilityName suppressions the VulnerabilitySuppressionAnalyzer runs with the same 508 CPE suppression rules that the CPESuppressionAnalyzer uses
```
[WARNING] CpeSuppressionAnalyzer with 508 suppressionRules
...
[WARNING] VulnerabilitySuppressionAnalyzer with 508 suppressionRules
```

The base suppressions have 560 rules, 49 contain only CVEs, 3 only vulnerabiltyNames, 502 only CPE and 6 a mixture of CPE and CVE. So out of the 58 rules that VulnerabilitySuppressionAnalyzer should take into account only the 6 that also have CPE suppressions are taken into account.

So filtering out the applicable rules needs to move from rules-loading to suppression processing evaluation or we need separate CPE and vulnerabilitySuppression ruleset singletons.

2022-08-17 11:57 UTC, aikebah requested changes
Looks good, some minor improvements requested

2022-08-17 11:57 UTC, aikebah commented on core/src/main/java/org/owasp/dependencycheck/analyzer/AbstractSuppressionAnalyzer.java
> +            }
A left-over counter from initial debugging? It is only ever written to, never used.

```suggestion
        for (SuppressionRule rule : rules.list()) {
            if (filter(rule)) {
                rule.process(dependency);
            }
```

2022-08-17 11:57 UTC, aikebah commented on core/src/main/java/org/owasp/dependencycheck/analyzer/AbstractSuppressionAnalyzer.java
> +     * <code>true</code>
@return documented to always retain true. And I think the description can be improved to be more clear on whether it indicates 'filtering out' or 'filtering in' of rules.
```suggestion
     * Determines whether a suppression rule should be retained when filtering a set of suppression rules for a concrete suppression analyzer.
     *
     * @param rule the suppression rule to evaluate
     * @return <code>true</code> if the rule should be retained; otherwise
     * <code>false<code>
```

2022-08-17 11:57 UTC, aikebah commented on core/src/main/java/org/owasp/dependencycheck/xml/suppression/SuppressionHandler.java
>      }
As this is the sole constructor and it's now empty it can be fully left out from the codebase.

2022-08-18 16:52 UTC, aikebah approved these changes

2022-08-18 16:53 UTC, merged