Remove FP for parseurl
dependency-check/DependencyCheck pull request #4714
Opened 2022-07-28 22:09 UTC by MisaelBustamante

Remove FP for parseurl

The following CVE's are making reference to [parse-url](https://github.com/IonicaBizau/parse-url) library.

[CVE-2022-2216](https://nvd.nist.gov/vuln/detail/CVE-2022-2216)
[CVE-2022-0722](https://nvd.nist.gov/vuln/detail/CVE-2022-0722)
[CVE-2022-2217](https://nvd.nist.gov/vuln/detail/CVE-2022-2217)
[CVE-2022-2218](https://nvd.nist.gov/vuln/detail/CVE-2022-2218)

2022-07-30 09:25 UTC, aikebah requested changes
Looks good, but needs base="true" added to the suppression element. Would've been good to reference the already registered issue for the same FP (updated the PR-comment already for that), so that this PR gets linked as solving that issue

2022-07-30 09:25 UTC, aikebah commented on core/src/main/resources/dependencycheck-base-suppression.xml
> +    <suppress>
```suggestion
    <suppress base="true">
```

Suppressions in the project's base suppression rules require the base attribute to be set to true.

2022-07-31 00:28 UTC, MisaelBustamante commented
@aikebah Suggestion applied, and thanks for adding the issue to the description, I had not seen it

2022-07-31 07:09 UTC, aikebah approved these changes

2022-07-31 07:09 UTC, merged