IssueOps: Generate Hosted Suppression File
dependency-check/DependencyCheck pull request #4784
Opened 2022-08-27 10:46 UTC by jeremylong

Implements the first half of #4723 - the workflow will commit the previously generated suppression rule to the `generatedSuppressions` suppression branch and publish the suppression file to `gh-pages` **if approved** by one of the core maintainers. Core maintainers can simply reply "approved" to the generated suppression rule in an issue labeled as a `FP Report` to kick off this workflow.

2022-08-29 10:22 UTC, jeremylong commented
Development and testing was done here: https://github.com/jeremylong/workflow-test/

Duplicate reports see: https://github.com/jeremylong/workflow-test/issues/4
Approving a suppression rule see: https://github.com/jeremylong/workflow-test/issues/6

2022-08-31 16:24 UTC, aikebah requested changes
Looks good to me, except for the approving-user-guard on the approve comment

2022-08-31 16:24 UTC, aikebah commented on .github/workflows/false-positive-approvals.yml
> +      contains(github.event.comment.user.login, 'nhumblot'))  }}
```suggestion
      (github.event.comment.user.login === 'jeremylong') ||
      github.event.comment.user.login === 'aikebah') || 
      github.event.comment.user.login === 'nhumblot'))  }}
```

Stronger check required to avoid people with github logins like `aikebah1337` impersonating as me. Derived the alternative check from the filter applied at line 41 to check whether a comment was made by the github actions bot. Not sure whether exact same check can be used for mere mortals with a github account

2022-09-02 09:45 UTC, jeremylong commented
@aikebah - thanks for catching the issue with the approvers!

2022-09-02 09:57 UTC, merged

2022-09-03 13:48 UTC, aikebah commented
@jeremylong The `===` syntax is invalid.... see https://github.com/jeremylong/DependencyCheck/actions/runs/2984591036