Fixing file separator bug for unit test on windows machines
dependency-check/DependencyCheck pull request #4795
Opened 2022-08-31 14:09 UTC by echalone

## Fixes Issue #
Fixed test for windows machines (backslash would escape a character, therefore it needs to be replaced with a double backslash if file separator is a backslash).

## Description of Change
Replacing potential backslash in File.separator property with double-backslash so it won't throw an exception on windows machines (or other OS using backslash instead of slash as path separator).

## Have test cases been added to cover the new functionality?
Technically no, because it fixes a test case itself.

2022-09-01 22:11 UTC, aikebah requested changes

2022-09-01 22:11 UTC, aikebah commented on core/src/test/java/org/owasp/dependencycheck/analyzer/DependencyCheckPropertiesTest.java
> +        String parsedPackageName = packageName.replaceAll("[.]", File.separator.replaceAll("\\\\","\\\\\\\\"));
```suggestion
        String parsedPackageName = packageName.replaceAll("[.]", "/");
```

As the resourceloader is used the proper fix should be replacing `.` by forward slash see [getResources javadoc](https://docs.oracle.com/javase/8/docs/api/java/lang/ClassLoader.html#getResources-java.lang.String-)

2022-09-02 09:52 UTC, jeremylong approved these changes

2022-09-02 16:56 UTC, aikebah approved these changes

2022-09-02 16:56 UTC, merged