Add CISA Known Exploited Vulnerability Catalog
dependency-check/DependencyCheck pull request #4895
Opened 2022-09-30 10:12 UTC by jeremylong

### Enhancement #4878

Adds a new datasource for the CISA Known Exploited Vulnerability Catalog and adds the information to the reports for any known exploited vulnerability that has been identified.

2022-09-30 10:13 UTC, jeremylong commented
For reviewers - I accidentally included some unrelated updates suggested by checkstyle.

2022-11-13 23:02 UTC, aikebah reviewed
Still plan for a second round of review... as I didn't manage to cover all changes yet

2022-11-13 23:02 UTC, aikebah commented on core/src/main/resources/data/dbStatements.properties
> +SELECT_KNOWN_EXPLOITED_VULNERABILITIES=SELECT * FROM knownExploited
```suggestion
SELECT_KNOWN_EXPLOITED_VULNERABILITIES=SELECT cveID, vendorProject, product, vulnerabilityName, dateAdded, shortDescription, requiredAction, dueDate,notes
 FROM knownExploited
```

As the fields get accessed by index on the query-result I think the query should be explicit on the columns.

https://github.com/jeremylong/DependencyCheck/blob/4343b1a1063e9c6443bbe1d96d0a797dc738ddcc/core/src/main/java/org/owasp/dependencycheck/data/nvdcve/CveDB.java#L1451-L1459

2022-11-13 23:02 UTC, aikebah commented on core/src/main/resources/data/initialize_postgres.sql
> +IF EXISTS(SELECT * FROM knownExploited WHERE cveID=p_cveID) THEN
```suggestion
IF EXISTS(SELECT 1 FROM knownExploited WHERE cveID=p_cveID) THEN
```

No need to retrieve existing values (and make PostgreSQL allocate memory for it) as they get discarded anyhow.

2022-11-13 23:02 UTC, aikebah commented on core/src/main/resources/data/initialize_mssql.sql
> +CREATE TABLE knownExploited (cveID varchar(20),
```suggestion
CREATE TABLE knownExploited (cveID varchar(20) PRIMARY KEY,
```
Missing primary-key clause

2022-11-13 23:02 UTC, aikebah commented on core/src/main/resources/data/initialize_mysql.sql
> +CREATE TABLE knownExploited (cveID varchar(20),
```suggestion
CREATE TABLE knownExploited (cveID varchar(20) PRIMARY KEY ,
```

Missing primary-key clause

2022-11-13 23:02 UTC, aikebah commented on core/src/main/resources/data/initialize_mysql.sql
> +       ON DUPLICATE KEY UPDATE `cveID`=p_cveID;
From https://dev.mysql.com/doc/refman/8.0/en/insert-on-duplicate.html I deduce that this will not do what you expect it to do. In case of duplicates it will only do a (no-op) update of the primary key from what I see on that page.

I believe the proper clause would be:
```SQL
ON DUPLICATE KEY UPDATE `vendorProject`=VALUES(`vendorProject`),`product`=VALUES(`product`),etc.
```
OR

```SQL
ON DUPLICATE KEY UPDATE `vendorProject`=p_vendorProject,`product`=p_product,etc.
```

If `ON DUPLICATE KEY UPDATE` would really update all columns I would expect their first example to read

```SQL
INSERT INTO t1 (a,b,c) VALUES (1,2,3)
  ON DUPLICATE KEY UPDATE c=c+1;

UPDATE t1 SET b=2, c=c+1 WHERE a=1;
```
as their introductiory text only requires the presence of a row with a=1 and makes no prerequisites on the value of column b it should be expected that column b is left intact by the `INSERT ... ON DUPLICATE UPDATE` statement as they state that in the presence of a row with a=1 both queries yield the same end-result in the database.

2022-11-13 23:02 UTC, aikebah commented on core/src/main/resources/data/initialize_oracle.sql
> +CREATE TABLE knownExploited (cveID varchar(20),
```suggestion
CREATE TABLE knownExploited (cveID varchar(20) PRIMARY KEY,
```
Missing primary key clause

2022-11-13 23:02 UTC, aikebah commented on core/src/main/resources/data/initialize_postgres.sql
> +CREATE TABLE knownExploited (cveID varchar(20),
```suggestion
CREATE TABLE knownExploited (cveID varchar(20) PRIMARY KEY,
```
Missing primary key clause

2022-11-13 23:02 UTC, aikebah commented on core/src/main/java/org/owasp/dependencycheck/data/nvdcve/CveDB.java
> +        MERGE_KNOWN_VULNERABLE
Maybe better to rename both here and in the SQLs to MERGE_KNOWN_EXPLOITED

2022-12-03 22:32 UTC, aikebah requested changes

2022-12-03 22:32 UTC, aikebah commented on core/src/main/java/org/owasp/dependencycheck/data/update/KnownExploitedDataSource.java
> +            }
As the exception-handling is identical I agree with my IDE that there is no sense in giving them separate catch-blocks

```suggestion
            } catch (TooManyRequestsException | ResourceNotFoundException | IOException
                    | CorruptedDatastreamException | DatabaseException | SQLException ex) {
                throw new UpdateException(ex);
            }
```

2022-12-03 22:32 UTC, aikebah commented on core/src/main/java/org/owasp/dependencycheck/data/update/cisa/KnownExploitedVulnerabilityParser.java
> +        objectMapper.registerModule(new AfterburnerModule());
Like the NvdCveParser (in current main branch) we should use Blackbird on Java8

```suggestion
        final Module module;
        if (getJavaVersion() <= 8) {
            module = new AfterburnerModule();
        } else {
            module = new BlackbirdModule();
        }
        objectMapper.registerModule(module)
```
adding also the getJavaVersion(), or, maybe better, centralize it in a utility-class.

2022-12-03 22:32 UTC, aikebah commented on core/src/main/java/org/owasp/dependencycheck/dependency/Vulnerability.java
> +     * null null     {@code &lt;CVSSv3 critical> >> &lt;Unscored recognized critical> >>
```suggestion
     * {@code &lt;CVSSv3 critical> >> &lt;Unscored recognized critical> >>
```
Looks like an accidental edit

2022-12-03 22:32 UTC, aikebah commented on core/src/main/java/org/owasp/dependencycheck/reporting/ReportTool.java
> +                sb.append("Requied Action").append(knownExploitedVulnerability.getRequiredAction()).append("\n");
```suggestion
                sb.append("Required Action: ").append(knownExploitedVulnerability.getRequiredAction()).append("\n");
```

2022-12-03 22:32 UTC, aikebah commented on core/src/main/java/org/owasp/dependencycheck/reporting/ReportTool.java
> +                sb.append("notes").append(knownExploitedVulnerability.getNotes()).append("\n");
```suggestion
                sb.append("Notes: ").append(knownExploitedVulnerability.getNotes()).append("\n");
```

2022-12-03 22:32 UTC, aikebah commented on core/src/main/java/org/owasp/dependencycheck/reporting/ReportTool.java
> +                sb.append("Short Description").append(knownExploitedVulnerability.getShortDescription()).append("\n");
```suggestion
                sb.append("Short Description: ").append(knownExploitedVulnerability.getShortDescription()).append("\n");
```

2022-12-03 22:32 UTC, aikebah commented on core/src/main/resources/data/dbStatements.properties
> +MERGE_KNOWN_VULNERABLE=CALL merge_knownexpoited(?,?,?,?,?,?,?,?,?)
```suggestion
MERGE_KNOWN_VULNERABLE=CALL merge_knownexploited(?,?,?,?,?,?,?,?,?)
```

2022-12-03 22:32 UTC, aikebah commented on core/src/main/resources/data/dbStatements_mariadb.properties
> +MERGE_KNOWN_VULNERABLE=CALL merge_knownexpoited(?,?,?,?,?,?,?,?,?);
```suggestion
MERGE_KNOWN_VULNERABLE=CALL merge_knownexploited(?,?,?,?,?,?,?,?,?);
```

2022-12-03 22:32 UTC, aikebah commented on core/src/main/resources/data/dbStatements_microsoft sql server.properties
> +MERGE_KNOWN_VULNERABLE=EXEC merge_knownexpoited ?, ?, ?, ?, ?, ?, ?, ?, ?
```suggestion
MERGE_KNOWN_VULNERABLE=EXEC merge_knownexploited ?, ?, ?, ?, ?, ?, ?, ?, ?
```

2022-12-03 22:32 UTC, aikebah commented on core/src/main/resources/data/dbStatements_mysql.properties
> +MERGE_KNOWN_VULNERABLE=CALL merge_knownexpoited(?,?,?,?,?,?,?,?,?);
```suggestion
MERGE_KNOWN_VULNERABLE=CALL merge_knownexploited(?,?,?,?,?,?,?,?,?);
```

2022-12-03 22:32 UTC, aikebah commented on core/src/main/resources/data/dbStatements_oracle.properties
> +MERGE_KNOWN_VULNERABLE={ CALL merge_knownexpoited(?,?,?,?,?,?,?,?,?) }
```suggestion
MERGE_KNOWN_VULNERABLE={ CALL merge_knownexploited(?,?,?,?,?,?,?,?,?) }
```

2022-12-03 22:32 UTC, aikebah commented on core/src/main/resources/data/upgrade_5.2.1.sql
> +CREATE ALIAS merge_knownexpoited FOR "org.owasp.dependencycheck.data.nvdcve.H2Functions.mergeKnownExploited";
```suggestion
CREATE ALIAS merge_knownexploited FOR "org.owasp.dependencycheck.data.nvdcve.H2Functions.mergeKnownExploited";
```

2022-12-03 22:32 UTC, aikebah commented on core/src/main/resources/data/dbStatements_postgresql.properties
> +MERGE_KNOWN_VULNERABLE=CALL merge_knownexpoited(?,?,?,?,?,?,?,?,?);
```suggestion
MERGE_KNOWN_VULNERABLE=CALL merge_knownexploited(?,?,?,?,?,?,?,?,?);
```

2022-12-03 22:32 UTC, aikebah commented on core/src/main/resources/data/initialize.sql
> +CREATE ALIAS merge_knownexpoited FOR "org.owasp.dependencycheck.data.nvdcve.H2Functions.mergeKnownExploited";
```suggestion
CREATE ALIAS merge_knownexploited FOR "org.owasp.dependencycheck.data.nvdcve.H2Functions.mergeKnownExploited";
```

2022-12-03 22:32 UTC, aikebah commented on core/src/main/resources/data/initialize_mssql.sql
> +CREATE PROCEDURE merge_knownexpoited (@cveID varchar(20),
```suggestion
CREATE PROCEDURE merge_knownexploited (@cveID varchar(20),
```

2022-12-03 22:32 UTC, aikebah commented on core/src/main/resources/data/initialize_mysql.sql
> +CREATE PROCEDURE merge_knownexpoited
```suggestion
CREATE PROCEDURE merge_knownexploited
```

2022-12-03 22:32 UTC, aikebah commented on core/src/main/resources/data/initialize_oracle.sql
> +CREATE OR REPLACE PROCEDURE merge_knownexpoited(
```suggestion
CREATE OR REPLACE PROCEDURE merge_knownexploited(
```

2022-12-03 22:32 UTC, aikebah commented on core/src/main/resources/data/initialize_postgres.sql
> +CREATE FUNCTION merge_knownexpoited (
```suggestion
CREATE FUNCTION merge_knownexploited (
```

2022-12-03 22:32 UTC, aikebah commented on core/src/main/resources/templates/csvReport.vsl
> +$enc.csv($applicationName),$enc.csv($scanDate),$enc.csv($dependency.DisplayFileName),$enc.csv($dependency.FilePath),$enc.csv($dependency.description),$enc.csv($dependency.license),#if(!$dependency.is
```suggestion
$enc.csv($applicationName),$enc.csv($scanDate),$enc.csv($dependency.DisplayFileName),$enc.csv($dependency.FilePath),$enc.csv($dependency.description),$enc.csv($dependency.license),#if(!$dependency.isVirtual())$enc.csv($dependency.Md5sum)#else""#end,#if(!$dependency.isVirtual())$enc.csv($dependency.Sha1sum)#else""#end,$enc.csvIdentifiers($dependency.softwareIdentifiers),$enc.csvIdentifiers($dependency.vulnerableSoftwareIdentifiers),$enc.csv($vuln.name),$enc.csv($vuln.getCwes().toString()),$enc.csv($vuln.description),$enc.csv($vuln.getSource().name()),#if($vuln.cvssV2)$enc.csv($vuln.cvssV2.severity)#else""#end,#if($vuln.cvssV2)$enc.csv($vuln.cvssV2.score)#else""#end,#if($vuln.cvssV2)$enc.csv($vuln.cvssV2.toString())#else""#end,#if($vuln.cvssV3)$enc.csv($vuln.cvssV3.baseSeverity)#else""#end,#if($vuln.cvssV3)$enc.csv($vuln.cvssV3.baseScore)#else""#end,#if($vuln.cvssV3)$enc.csv($vuln.cvssV3.toString())#else""#end,$enc.csvCpeConfidence($dependency.softwareIdentifiers),$dependency.size(),#if($vuln.getKnownExploitedVulnerability())$enc.csv($vuln.getKnownExploitedVulnerability().getVendorProject()),$enc.csv($vuln.getKnownExploitedVulnerability().getProduct()),$enc.csv($vuln.getKnownExploitedVulnerability().getVulnerabilityName()),$enc.csv($vuln.getKnownExploitedVulnerability().getDateAdded()),$enc.csv($vuln.getKnownExploitedVulnerability().getShortDescription()),$enc.csv($vuln.getKnownExploitedVulnerability().getRequiredAction()),$enc.csv($vuln.getKnownExploitedVulnerability().getDueDate()),$enc.csv($vuln.getKnownExploitedVulnerability().getNotes())#else"","","","","","","",""#end
```
Only dereference getKnownExploitedVulnerability() in template when non-null

2022-12-03 22:32 UTC, aikebah commented on core/src/main/resources/templates/htmlReport.vsl
> +            This report may contain data retrieved ßfrom the <a href="https://www.cisa.gov/known-exploited-vulnerabilities-catalog">CISA Known Exploited Vulnerabilities Catalog</a>.
```suggestion
            This report may contain data retrieved from the <a href="https://www.cisa.gov/known-exploited-vulnerabilities-catalog">CISA Known Exploited Vulnerabilities Catalog</a>.
```

2022-12-03 22:32 UTC, aikebah commented on core/src/main/java/org/owasp/dependencycheck/analyzer/KnownExploitedVulnerabilityAnalyzer.java
> +            this.knownExploited = engine.getDatabase().getknownExploitedVulnerabilities();
Loading all in memory looks fine for now and will reduce query-load, but we should watch catalog growth and change to a query-on-demand when this would be an excessive usage of memory.

2022-12-04 11:26 UTC, jeremylong commented on core/src/main/java/org/owasp/dependencycheck/analyzer/KnownExploitedVulnerabilityAnalyzer.java
> +            this.knownExploited = engine.getDatabase().getknownExploitedVulnerabilities();
There may be a change to how the CISA data is loaded and used when we move to the NVD APIs - as the APIs have this data included and linked to each CVE.

2023-01-09 10:40 UTC, jeremylong commented on core/src/main/resources/data/initialize_mysql.sql
> +       ON DUPLICATE KEY UPDATE `cveID`=p_cveID;
Thanks! this has been corrected.

2023-01-10 22:31 UTC, aikebah approved these changes

2023-01-11 10:19 UTC, merged

2023-01-11 10:54 UTC, jeremylong commented
@aikebah all of the 8.0.0 PRs are merged. I will need to add one more thing for the KEV - a switch to disable the datafeed and analysis that is exposed to the cli, plugins, etc.