Scan Maven Plugins
dependency-check/DependencyCheck pull request #5001
Opened 2022-10-29 11:36 UTC by jeremylong

## Fixes Issue #4035

Adds the ability to scan the plugins of a Maven project (via the org.owasp:dependency-check-maven plugin - not the CLI).
- Introduced `includedBy` to the HTML, XML, and JSON reports when scanning with the Maven Plugin. `includedBy` is the root of the dependency tree (i.e. if a transitive dependency is scanned, the `includedBy` will be a direct dependency). Note that when using the maven plugin `includedBy` will be added even when plugins are not scanned.

2022-10-29 13:31 UTC, mprins requested changes

2022-10-29 13:31 UTC, mprins commented on maven/src/main/java/org/owasp/dependencycheck/maven/BaseDependencyCheckMojo.java
> +     * The name of the report in the site.
```suggestion
     * Whether the project plugins should also be scanned.
```

2022-10-31 09:47 UTC, jeremylong commented
@mprins thanks for the suggestion!

2022-11-13 18:57 UTC, aikebah commented on core/src/main/resources/schema/dependency-check.2.5.xsd
> +                    <xs:sequence minOccurs="0" maxOccurs="unbounded">
Would expect only one of these optional, that is: either require an optionally empty element includedBy, or require that when includedBy is present there is at least one reference.

2022-11-13 20:01 UTC, aikebah commented on maven/src/main/java/org/owasp/dependencycheck/maven/BaseDependencyCheckMojo.java
> +            //final CollectingDependencyNodeVisitor collectorVisitor = new CollectingDependencyNodeVisitor();
```suggestion
```

Remove the commented old code

2022-11-13 20:01 UTC, aikebah commented on maven/src/main/java/org/owasp/dependencycheck/maven/BaseDependencyCheckMojo.java
> +     * and scanning the dependencies
```suggestion
     * Scans the project's artifacts for plugin-dependencies and adds them to the engine's dependency
     * list.
     *
     * @param project the project to scan the plugin-dependencies of
     * @param engine the engine to use to scan the plugin-dependencies
     * @param exCollection the collection of exceptions that have previously
     * occurred
     * @return a collection of exceptions that may have occurred while resolving
     * and scanning the plugins and their dependencies
```

2022-11-13 20:01 UTC, aikebah commented on maven/src/main/java/org/owasp/dependencycheck/maven/BaseDependencyCheckMojo.java
> +                            //TODO convert to package URL
Any reason to not immediately start using the pURL?

2022-11-13 20:01 UTC, aikebah commented on maven/src/main/java/org/owasp/dependencycheck/maven/BaseDependencyCheckMojo.java
> +                //TOOD - convert this to a packageURl instead of GAV
Any reason to not immediately start using the pURL?

2022-11-13 20:01 UTC, aikebah commented on maven/src/main/java/org/owasp/dependencycheck/maven/BaseDependencyCheckMojo.java
> +                //TODO - consider packageUrL
Any reason to not immediately start using the pURL?

2022-11-13 20:01 UTC, aikebah commented on maven/src/main/java/org/owasp/dependencycheck/maven/BaseDependencyCheckMojo.java
> +    }
Will review these in a second round as the GitHub UI doesn't recognize it as (what at first glance it appears to be) a factored-out helper method, so I'll invoke the help of a local IDE to see what the material changes are.

2022-11-13 21:00 UTC, aikebah commented on maven/src/main/java/org/owasp/dependencycheck/maven/BaseDependencyCheckMojo.java
> +                    //TODO ensure root is passed in so we can assign parent
Still needs to be addressed I think

2022-11-13 21:00 UTC, aikebah commented on maven/src/main/java/org/owasp/dependencycheck/maven/BaseDependencyCheckMojo.java
> +                //TODO convert to packageURL
Any reason to not immediately start using the pURL?

2022-11-13 21:00 UTC, aikebah commented on maven/src/main/java/org/owasp/dependencycheck/maven/BaseDependencyCheckMojo.java
> +                //TODO convert to packageURL
Any reason to not immediately start using the pURL?

2022-11-13 21:00 UTC, aikebah commented on maven/src/main/java/org/owasp/dependencycheck/maven/BaseDependencyCheckMojo.java
> +                    //TODO convert to package URL
Any reason to not immediately start using the pURL?

2022-11-13 21:00 UTC, aikebah commented on maven/src/main/java/org/owasp/dependencycheck/maven/BaseDependencyCheckMojo.java
> +                //TODO convert to packageURL
Any reason to not immediately start using the pURL?

2022-11-13 21:00 UTC, aikebah commented on maven/src/main/java/org/owasp/dependencycheck/maven/BaseDependencyCheckMojo.java
> +                //TODO convert to packageURL
Any reason to not immediately start using the pURL?

2022-11-13 21:20 UTC, aikebah commented on maven/src/main/java/org/owasp/dependencycheck/maven/BaseDependencyCheckMojo.java
> +                    //TODO ensure root is passed in so we can assign parent
```suggestion
```
If my understanding is correct it is already addressed by
https://github.com/jeremylong/DependencyCheck/blob/fdc8896ec749c8f865e47ed529e58affa9bc7e0d/maven/src/main/java/org/owasp/dependencycheck/maven/BaseDependencyCheckMojo.java#L1718-L1721

2022-12-03 19:41 UTC, aikebah requested changes
Reviews that should be addressed before merge in my view are :
https://github.com/jeremylong/DependencyCheck/pull/5001/files/fdc8896ec749c8f865e47ed529e58affa9bc7e0d#r1020950469

and 
https://github.com/jeremylong/DependencyCheck/pull/5001/files/fdc8896ec749c8f865e47ed529e58affa9bc7e0d#r1020965735

2023-01-01 11:34 UTC, jeremylong commented on core/src/main/resources/schema/dependency-check.2.5.xsd
> +                    <xs:sequence minOccurs="0" maxOccurs="unbounded">
so you suggestion would be:

```suggestion
            <xs:element name="includedBy" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                    <xs:sequence maxOccurs="unbounded">
```

2023-01-01 11:37 UTC, jeremylong commented on maven/src/main/java/org/owasp/dependencycheck/maven/BaseDependencyCheckMojo.java
> +                            //TODO convert to package URL
I guess this should have been a draft PR as I was planning on switching over to the package URL before publication.

2023-01-01 14:20 UTC, aikebah commented on core/src/main/resources/schema/dependency-check.2.5.xsd
> +                    <xs:sequence minOccurs="0" maxOccurs="unbounded">
correct

2023-01-04 11:41 UTC, jeremylong commented on maven/src/main/java/org/owasp/dependencycheck/maven/BaseDependencyCheckMojo.java
> +                            //TODO convert to package URL
@aikebah I've been working on the gradle side - and I just started with the package URLs. However, I need an opinion on how we construct them. Currently, the maven plugin will add "(plugins)" to the package/scope reference and the included by references. If we are using package URL for the included by - would it be better to have:

```
aho-corasick-double-array-trie-1.2.3.jar
Referenced In Project/Scope: dependency-check-gradle-test:classpath (buildEnv)
Included by: pkg:maven/org.owasp/dependency-check-gradle@8.0.0-RC1 (buildEnv)
```

Which would make the includedBy in the JSON, XML, etc. formats not really comply... Or would using a qualifier in the packageUrL be better? 

```
aho-corasick-double-array-trie-1.2.3.jar
Referenced In Project/Scope: dependency-check-gradle-test:classpath (buildEnv)
Included by: pkg:maven/org.owasp/dependency-check-gradle@8.0.0-RC1?location=buildEnv
```

I'm leaning towards adding a qualifier - but I'm not sure I like `location`...  thoughts?

2023-01-04 11:44 UTC, jeremylong commented on maven/src/main/java/org/owasp/dependencycheck/maven/BaseDependencyCheckMojo.java
> +                            //TODO convert to package URL
Maybe `context`, `source`, or `type`?

2023-01-04 12:01 UTC, aikebah commented on maven/src/main/java/org/owasp/dependencycheck/maven/BaseDependencyCheckMojo.java
> +                            //TODO convert to package URL
I think adding the suffix would be the better option. In my reading the package-url should be a url containing everything to correctly identify the package to use. As such qualifiers like a repo-location (sampled in the examples of the purl spec) are appropriate (as sometimes a repo may have stored a slightly different package, which means you need to know the repo to select the appropriate package)

However 'the reason why something was included in the analyzed dependencies' is not something that relates to the proper identification and location of a software package in my view (the software package itself is still just a jar-file in a maven repo), so it would have no place in the purl qualifiers.

2023-01-05 10:42 UTC, jeremylong commented on maven/src/main/java/org/owasp/dependencycheck/maven/BaseDependencyCheckMojo.java
> +                            //TODO convert to package URL
I was thinking a qualifier would be okay as it helps identify, at a project level, how it was brought in. Was it from the dependencies (aka DependencyManagement) or build environment (aka PluginManagement). The repositories for each, at least in gradle, can be different.

2023-01-05 19:22 UTC, aikebah commented on maven/src/main/java/org/owasp/dependencycheck/maven/BaseDependencyCheckMojo.java
> +                            //TODO convert to package URL
> The repositories for each, at least in gradle, can be different.

For maven as well.. there are separate settings for pluginRepositories

But package-urls are meant to describe in a context-insensitive way what package is referenced. It would be good to honor the note of the spec:
> Note: Do not abuse qualifiers: it can be tempting to use many qualifier keys but their usage should be limited to the bare minimum for proper package identification

2023-01-09 11:29 UTC, jeremylong commented on maven/src/main/java/org/owasp/dependencycheck/maven/BaseDependencyCheckMojo.java
> +                            //TODO convert to package URL
resolved with https://github.com/jeremylong/DependencyCheck/pull/5001/commits/fb7d729039ea93e5322cbb8e8ccc9bfd04f89496

2023-01-09 12:46 UTC, jeremylong commented
@aikebah I think I'm good with the 8.0.0 PRs now. Planning on spending this week integrating the 8.0.0 PRs and testing so we can finally get these released. Please let me know if you see any additional issues/concerns.

2023-01-10 22:13 UTC, aikebah requested changes
See review, think we should stay on the safe side with internal Maven vars.... with that integrated all looks good to me

2023-01-10 22:13 UTC, aikebah commented on maven/src/main/java/org/owasp/dependencycheck/maven/BaseDependencyCheckMojo.java
> +        plugins.addAll(extensions);
```suggestion
        final Set<Artifact> plugins = new HashSet<>();
        final Set<Artifact> buildPlugins = getProject().getPluginArtifacts();
        final Set<Artifact> reportPlugins = getProject().getReportArtifacts();
        final Set<Artifact> extensions = getProject().getExtensionArtifacts();

        plugins.addAll(buildPlugins);
        plugins.addAll(reportPlugins);
        plugins.addAll(extensions);
```

As MavenProject exposes it's internal pluginArtifacts Set member, which is generated once and re-used on subsequent invocations of getPluginArtifacts() I think we should not add to it, but build our own set of the build plugin, reporting plugin and extension artifact sets.

2023-01-10 22:36 UTC, aikebah approved these changes

2023-01-10 22:38 UTC, aikebah commented
@jeremylong I'll leave the merge-sequence decision up to you.... my gut feel would be first the Known exploited and then the maven plugin would be the easiest to resolve any emerging merge conflicts

2023-01-11 10:44 UTC, merged

2023-01-23 23:19 UTC, pitprok commented
Based on this [dependency-check-sonar-plugin#748](https://github.com/dependency-check/dependency-check-sonar-plugin/issues/748)  `includedBy` broke the parsing of the reports.

`[INFO] 17:06:11.358 Using JSON-Reportparser
[WARNING] 17:06:11.651 JSON-Analysis aborted
[DEBUG] 17:06:11.653 Problem with JSON-Report-Mapping
org.sonar.dependencycheck.parser.ReportParserException: Problem with JSON-Report-Mapping
	at org.sonar.dependencycheck.parser.JsonReportParserHelper.parse(JsonReportParserHelper.java:44)
	at org.sonar.dependencycheck.DependencyCheckSensor.parseAnalysis(DependencyCheckSensor.java:71)
	at org.sonar.dependencycheck.DependencyCheckSensor.execute(DependencyCheckSensor.java:150)
	at org.sonar.scanner.sensor.AbstractSensorWrapper.analyse(AbstractSensorWrapper.java:48)
	at org.sonar.scanner.sensor.ProjectSensorsExecutor.execute(ProjectSensorsExecutor.java:49)
	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:360)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:137)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:123)
	at org.sonar.scanner.bootstrap.GlobalContainer.doAfterStart(GlobalContainer.java:150)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:137)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:123)
	at org.sonar.batch.bootstrapper.Batch.doExecute(Batch.java:72)
	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:66)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy45.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:189)
	at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:138)
	at org.sonarsource.scanner.maven.bootstrap.ScannerBootstrapper.execute(ScannerBootstrapper.java:65)
	at org.sonarsource.scanner.maven.SonarQubeMojo.execute(SonarQubeMojo.java:108)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "includedBy" (class org.sonar.dependencycheck.parser.element.Dependency), not marked as ignorable (9 known properties: "filePath", "evidenceCollected", "sha1", "fileName", "vulnerabilities", "vulnerabilityIds", "packages", "md5", "identifiers"])
 at [Source: (sun.nio.ch.ChannelInputStream); line: 1, column: 6225] (through reference chain: org.sonar.dependencycheck.parser.element.Analysis["dependencies"]->java.util.ArrayList[0]->org.sonar.dependencycheck.parser.element.Dependency["includedBy"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:855)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1212)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1604)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperties(BeanDeserializerBase.java:1554)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:511)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1322)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:331)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:164)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:290)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:249)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:26)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:542)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:535)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:419)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1322)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:331)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:164)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4526)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3505)
	at org.sonar.dependencycheck.parser.JsonReportParserHelper.parse(JsonReportParserHelper.java:40)
	... 45 common frames omitted`
	
Is there a way to disable that field or do we have to wait for it to be fixed?