Update Dart Analyzer
dependency-check/DependencyCheck pull request #5011
Opened 2022-11-02 10:46 UTC by jeremylong

## Fixes Issue #5008

* Adds checks for empty/non-existent elements.
* Don't process yaml if lock is present (yaml may have blank versions)

2022-11-02 17:46 UTC, aikebah requested changes

2022-11-02 17:46 UTC, aikebah commented on core/src/main/java/org/owasp/dependencycheck/analyzer/DartAnalyzer.java
> +            final String dartVersion = rootNode.get("environment").get("sdk").textValue();
Think this should have null checks as well? 
Not familiar with the Dart ecosystem, but https://dart.dev/tools/pub/pubspec
and the readme for environment property hint to me that the elements may also be unavailable (for packages for Dart version <2.0)

2022-11-03 09:21 UTC, jeremylong commented on core/src/main/java/org/owasp/dependencycheck/analyzer/DartAnalyzer.java
> +            final String dartVersion = rootNode.get("environment").get("sdk").textValue();
Good catch - thanks!

2022-11-03 20:15 UTC, aikebah approved these changes

2022-11-04 08:33 UTC, merged