Fix: long version of go dependency unable to inserted into software table (CVE-2020-36569)
dependency-check/DependencyCheck pull request #5221
Opened 2023-01-06 07:31 UTC by srini00088

## Fixes Issue #
Fix: long version of go dependency unable to inserted into software table (CVE-2020-36569) 

## Description of Change
Alter's column size to varchar 75

*Please add a description of the proposed change*
Alters to a minimum possible value of version columns to 75 characters. Could be more or less as well.

## Have test cases been added to cover the new functionality?

no

2023-01-06 07:46 UTC, Fritzybois approved these changes

2023-01-06 07:50 UTC, gregoranders commented
commit message should start with a lowercase fix otherwise the pipeline breaks @srini00088

2023-01-06 07:57 UTC, vignesh-gupta approved these changes
Hey there, I believe this would be really help for one of the current issues i.e. issue with 'CVE-2020-36569' without harming any other.

2023-01-06 08:06 UTC, srini00088 commented
@gregoranders thanks, have amended the commit message

2023-01-06 08:11 UTC, vignesh-gupta-xom commented
@srini00088 please add space and commit is with small letter.

2023-01-06 08:12 UTC, vignesh-gupta approved these changes

2023-01-06 08:18 UTC, DUD3-droid approved these changes
@srini00088 kudos to you great job. Proactively solves the issue. I believe this will solve the issue

2023-01-06 08:33 UTC, jgavignet approved these changes

2023-01-06 08:33 UTC, jgavignet approved these changes

2023-01-06 08:41 UTC, gpx-jonathan-amos commented
Any tentative timelines on when this fix can get released? It's critical.

2023-01-06 09:42 UTC, marcelstoer commented
AFAICS this ain't complete yet. You need to modify `dependencycheck.properties` as per https://github.com/jeremylong/DependencyCheck/blob/main/core/src/main/resources/dependencycheck.properties#L21-L24.

2023-01-06 09:50 UTC, pvroegh approved these changes

2023-01-06 09:52 UTC, wilkovanderveen approved these changes
Seems right

2023-01-06 10:16 UTC, Nacadamia commented
How about a longer field than 75. Lets crank it up to at least 100 to buy some time.

2023-01-06 10:50 UTC, Nacadamia commented on core/src/main/resources/data/upgrade_5.3.sql
> +ALTER TABLE software ALTER COLUMN versionEndExcluding SET DATA TYPE VARCHAR(75);
I'd suggest a higher number than 75, because it is the exact the size for this specific entry.

2023-01-06 10:54 UTC, marcelstoer requested changes

2023-01-06 10:54 UTC, marcelstoer commented on core/src/main/resources/data/upgrade_5.3.sql
> +ALTER TABLE software ALTER COLUMN versionStartIncluding SET DATA TYPE VARCHAR(75);
```suggestion
ALTER TABLE software ALTER COLUMN versionEndExcluding SET DATA TYPE VARCHAR(100);
ALTER TABLE software ALTER COLUMN versionEndIncluding SET DATA TYPE VARCHAR(100);
ALTER TABLE software ALTER COLUMN versionStartExcluding SET DATA TYPE VARCHAR(100);
ALTER TABLE software ALTER COLUMN versionStartIncluding SET DATA TYPE VARCHAR(100);
```

2023-01-06 11:02 UTC, divertitoS approved these changes

2023-01-06 11:14 UTC, ottlinger commented
Wouldn't it be safer to trim any data read from CVE to not risk database length violations? Otherwise any faulty data in CVE entries will make the plugin fail again?

2023-01-06 11:17 UTC, Keymaster65 commented on core/src/main/resources/data/upgrade_5.3.sql
> +ALTER TABLE software ALTER COLUMN versionEndExcluding SET DATA TYPE VARCHAR(75);
How about 255 like other COLUMNs or even more. Is their a concret reason for 75 except that the current CVE needs 75?

2023-01-06 11:39 UTC, kaby2201 approved these changes

2023-01-06 11:41 UTC, jgavignet approved these changes

2023-01-06 11:48 UTC, nusmanov commented on core/src/main/resources/data/upgrade_5.3.sql
> +ALTER TABLE software ALTER COLUMN versionEndExcluding SET DATA TYPE VARCHAR(75);
as @Keymaster65 already suggested, i would also prefer to take the column length of 255 chars:

```suggestion
ALTER TABLE software ALTER COLUMN versionEndExcluding SET DATA TYPE VARCHAR(255);
ALTER TABLE software ALTER COLUMN versionEndIncluding SET DATA TYPE VARCHAR(255);
ALTER TABLE software ALTER COLUMN versionStartExcluding SET DATA TYPE VARCHAR(255);
ALTER TABLE software ALTER COLUMN versionStartIncluding SET DATA TYPE VARCHAR(255);
```

2023-01-06 12:00 UTC, nusmanov approved these changes

2023-01-06 12:00 UTC, nusmanov approved these changes

2023-01-06 12:00 UTC, lc-nyovchev approved these changes

2023-01-06 12:00 UTC, lc-nyovchev commented on core/src/main/resources/data/upgrade_5.3.sql
> +ALTER TABLE software ALTER COLUMN versionEndExcluding SET DATA TYPE VARCHAR(75);
I am all for `255`, at least I don't see a reason to not make it reasonably bigger, otherwise `75` is just us waiting for the next one to happen.

2023-01-06 12:00 UTC, lc-nyovchev commented on core/src/main/resources/data/upgrade_5.3.sql
> +ALTER TABLE software ALTER COLUMN versionStartIncluding SET DATA TYPE VARCHAR(75);
I'd say 255 is even more on the safe side, as @nusmanov [suggested](https://github.com/jeremylong/DependencyCheck/pull/5221/files#r1063375806):

2023-01-06 12:01 UTC, nusmanov approved these changes

2023-01-06 12:02 UTC, catap requested changes

2023-01-06 12:02 UTC, catap commented on core/src/main/resources/data/upgrade_5.3.sql
> +ALTER TABLE software ALTER COLUMN versionStartIncluding SET DATA TYPE VARCHAR(75);
```suggestion
ALTER TABLE software ALTER COLUMN versionEndExcluding SET DATA TYPE CHARACTER LARGE OBJECT;
ALTER TABLE software ALTER COLUMN versionEndIncluding SET DATA TYPE VARCHAR(75);
ALTER TABLE software ALTER COLUMN versionStartExcluding SET DATA TYPE CHARACTER LARGE OBJECT;
ALTER TABLE software ALTER COLUMN versionStartIncluding SET DATA TYPE CHARACTER LARGE OBJECT);
```

and lets forgot about that kind of issue forever.

2023-01-06 12:07 UTC, ThomasVerhoeven1998 approved these changes

2023-01-06 13:11 UTC, jjoshm commented
suggest that this be merged as a hotfix asap so that it works for now and be optimized and discussed afterwards.
The complexity seems manageable.

2023-01-06 13:22 UTC, jeremylong commented on core/src/main/resources/data/upgrade_5.3.sql
> +ALTER TABLE software ALTER COLUMN versionStartIncluding SET DATA TYPE VARCHAR(75);
I am already working on this. There are a few other changes as well.

2023-01-06 13:22 UTC, jeremylong commented
I will update this PR and release an update today.

2023-01-06 13:41 UTC, vincent-petit reviewed
I wonder that you should also update the type in the `create table software` in the `initialize[_xxx].sql` 
https://github.com/jeremylong/DependencyCheck/blob/main/core/src/main/resources/data/initialize.sql#L31

I don't know the project, but when these columns have been added to the table with the script `upgrade_5.1.sql` (https://github.com/jeremylong/DependencyCheck/blob/21b08b3b8368e224beeca346cfaa246ea8bb3ac9/core/src/main/resources/data/upgrade_5.1.sql#L1), they have been added in the create table too

2023-01-06 13:57 UTC, fransah approved these changes

2023-01-06 14:39 UTC, pijean-rca commented on core/src/main/resources/data/upgrade_5.3.sql
> +ALTER TABLE software ALTER COLUMN versionEndExcluding SET DATA TYPE VARCHAR(75);
Should not this file be named `upgrade_5.2.2.sql` ?

2023-01-06 14:50 UTC, pijean-rca commented on core/src/main/resources/dependencycheck.properties
> -data.version=5.2.1
This property is used to choose the update file (`org.owasp.dependencycheck.data.nvdcve.DatabaseManager#DB_STRUCTURE_UPDATE_RESOURCE`) when `h2` is used (org.owasp.dependencycheck.data.nvdcve.DatabaseManager#updateSchema).

Analysis crashes when the upgrade file does not exist. Along with my previous comment I would say that this property should be equal to `5.2.1`

2023-01-06 15:32 UTC, meridsa approved these changes

2023-01-06 16:10 UTC, 95Kevid approved these changes
Looks good to me

2023-01-06 16:37 UTC, aikebah commented on core/src/main/resources/dependencycheck.properties
> -data.version=5.2.1
It's not this property, but the database version property in your H2 database that governs which upgrade SQL is searched for. This property governs the expected database version (and if actual is lower than that will search for upgrade scripts to update the H2 database

2023-01-06 16:41 UTC, aikebah commented
> I will update this PR and release an update today.

@jeremylong did a fix-up of the update-script name, before spotting your response. Will leave the further polishing to you.

2023-01-06 16:41 UTC, srcimon approved these changes

2023-01-06 16:58 UTC, A-Fitz-Nelnet commented
Does [utils\src\test\resources\dependencycheck.properties](https://github.com/jeremylong/DependencyCheck/blob/main/utils/src/test/resources/dependencycheck.properties#L20) also need to be updated?

2023-01-06 16:59 UTC, closed without merging

2023-01-06 17:00 UTC, jeremylong commented
see https://github.com/jeremylong/DependencyCheck/pull/5229

2023-01-06 18:36 UTC, ltaboada1 commented
Could you please upgrade gradle plugin to 7.4.4 as well? Latest is still 7.4.3 https://plugins.gradle.org/plugin/org.owasp.dependencycheck

2023-01-06 22:12 UTC, marcthayer commented
> Could you please upgrade gradle plugin to 7.4.4 as well? Latest is still 7.4.3 https://plugins.gradle.org/plugin/org.owasp.dependencycheck

Looks like it's showing 7.4.4 now.

2023-01-09 08:04 UTC, DominicTulley commented
@jeremylong could you update the jenkins plugin too please?

2023-01-09 08:18 UTC, sreekanthops commented
@jeremylong same here, please update this to jenkins please

2023-01-09 09:00 UTC, sreekanthops commented
Thanks, I could see latest 7.4.4 in dependency check plugin
<img width="462" alt="Screenshot 2023-01-09 at 2 30 05 PM" src="https://user-images.githubusercontent.com/18322161/211271826-eb5793ec-1f47-4be1-8acd-1db4b1ace348.png">

2023-01-09 09:37 UTC, DominicTulley commented
Ah, I missed that.  Maybe the plugin didn't need updating.  Excellent.