fix: correct maven documentation
dependency-check/DependencyCheck pull request #5399
Opened 2023-01-30 12:39 UTC by jeremylong

Resolves #5392

2023-02-01 14:45 UTC, aikebah requested changes
Should also remove line 129, the skipProvidedScope in the POM-snippet.

2023-02-02 12:55 UTC, jeremylong commented
You ever look back on documentation you wrote and can't believe you wrote it as it was clearly wrong?  ugh...

2023-02-02 18:37 UTC, aikebah approved these changes

2023-02-02 18:40 UTC, aikebah commented
> You ever look back on documentation you wrote and can't believe you wrote it as it was clearly wrong? ugh...

Yes, unfortunately that sounds a bit too familiar to me :)

2023-02-02 18:40 UTC, merged