feat: Support msbuild Directory.build.props
dependency-check/DependencyCheck pull request #5475
Opened 2023-02-19 14:45 UTC by jeremylong

- partially resolves #1948
- removes unnecessary interfaces

2023-02-19 21:24 UTC, aikebah requested changes
Coding of interpolation is not in line with its documented behaviour (was previously already an error in interpolation method in the Model class).

2023-02-19 21:24 UTC, aikebah commented on core/src/main/java/org/owasp/dependencycheck/analyzer/MSBuildProjectAnalyzer.java
> +     * The phase fis which the analyzer runs.
```suggestion
     * The phase in which the analyzer runs.
```

2023-02-19 21:24 UTC, aikebah commented on core/src/main/java/org/owasp/dependencycheck/xml/pom/Model.java
> +        this.groupId = InterpolationUtil.interpolate(this.groupId, properties);
Be careful when merging/rebasing... main has changes removing the G/A/V interpolation from #5473 that should be retained

2023-02-19 21:24 UTC, aikebah commented on core/src/test/java/org/owasp/dependencycheck/utils/InterpolationUtilTest.java
> +
```suggestion

    @Test
    public void testInterpolateNonexistentErased() {
        Properties prop = new Properties();
        prop.setProperty("key", "value");
        String text = "This is a test of '${key}' and '${nothing}'";
        String expResults = "This is a test of 'value' and ''";
        String results = InterpolationUtil.interpolate(text, prop);
        assertEquals(expResults, results);
    }
```

Think it would be good to also explicitly test the erasure of non-existent property-references (as documented in the InterpolationUtil comments), to avoid them being accidentally retained as-is or replaced by `null`.

This addition will surface that the current coding is not not consistent with the documentation (as the result is currently `This is a test of 'value' and '${nothing}'`). So either the interpolation needs to be fixed, or the Javadoc comment needs to be updated to reflect the actual behaviour and my suggested addition needs to be updated to `testInterpolateNonexistentRetained` and prediction of the current actual result.

2023-02-19 21:24 UTC, aikebah commented on core/src/main/java/org/owasp/dependencycheck/utils/InterpolationUtil.java
> +    /**
Documentation is not consistent with actual behaviour, see review of the corresponding testcase

2023-02-19 21:24 UTC, aikebah commented on core/src/test/java/org/owasp/dependencycheck/utils/InterpolationUtilTest.java
> +
Would also be good to add duplicates for the MSBUILD SyntaxStyle interpolation (copies of the methods, but with braces instead of curly-braces and addition of the SyntaxStyle parameter to the interpolate call

2023-02-19 21:51 UTC, aikebah commented on core/src/main/java/org/owasp/dependencycheck/analyzer/MSBuildProjectAnalyzer.java
> +        final File propsProject = new File(parent, "Directory.Build.props");
According to the spec we should not load both (unless there is the import) and search up all the way to the root

https://learn.microsoft.com/en-us/visualstudio/msbuild/customize-your-build?view=vs-2019#search-scope

https://learn.microsoft.com/en-us/visualstudio/msbuild/customize-your-build?view=vs-2019#use-case-multi-level-merging

2023-02-20 15:01 UTC, jeremylong commented on core/src/main/java/org/owasp/dependencycheck/utils/InterpolationUtil.java
> +    /**
Fixed the `InterpolationUtil` to correctly return an empty string if the key is missing.

2023-02-20 15:02 UTC, jeremylong commented on core/src/main/java/org/owasp/dependencycheck/analyzer/MSBuildProjectAnalyzer.java
> +        final File propsProject = new File(parent, "Directory.Build.props");
I've attempted to implement the spec - best effort... Warnings will be logged for imports that cannot be followed.

2023-02-20 15:16 UTC, jeremylong commented on core/src/main/java/org/owasp/dependencycheck/xml/pom/Model.java
> +        this.groupId = InterpolationUtil.interpolate(this.groupId, properties);
I just rebased the branch from `main` and ensured your changes were kept.

2023-02-20 15:17 UTC, jeremylong commented on core/src/main/java/org/owasp/dependencycheck/analyzer/MSBuildProjectAnalyzer.java
> +            }
TODO - correct exception handling

2023-02-20 15:17 UTC, jeremylong commented on core/src/main/java/org/owasp/dependencycheck/data/nuget/DirectoryBuildPropsParser.java
> +        }
TODO - correct exception handling

2023-02-20 15:19 UTC, jeremylong commented
@aikebah thank you for the review and comments. Everything should be good to go now - with the exception of the error handling. I will update that in a day or two before finalizing and merging this PR.

2023-02-21 22:11 UTC, aikebah approved these changes

2023-02-21 22:24 UTC, aikebah commented
> @aikebah thank you for the review and comments. Everything should be good to go now - with the exception of the error handling. I will update that in a day or two before finalizing and merging this PR.

YW, always keen to try and find potential issues before features are introduced. Have made a habit of reading specs and checking whether code is matching specs (though reading the specs of the MSBuild documentation leaves and itchy feeling due to their free format open-endedness so that you can only 'try your best to conform to whatever Visual Studio happens to do'. 

I prefer the formal specs where you can really determine what is conformant and what not). I think your updated naive implementation is the best we can do (which covers the only usages that I would trust to reliably work now and in the future in my projects were I to be a dotnet developer with Visual Studio solutions projects given the documentation that Microsoft has put up for it)

2023-03-10 11:59 UTC, merged