#5919 feat: gitlab dependency scanner report format
dependency-check/DependencyCheck pull request #5920
Opened 2023-09-03 16:15 UTC by niklasfi

## Fixes Issue #5919

## Description of Change

As described in #5919, I am working on adding a new report format to DependencyCheck that can be directly fed to GitLab to be used as a dependency scanner in ci/cd-pipelines.

## Have test cases been added to cover the new functionality?

no

2023-09-03 16:19 UTC, niklasfi commented
Hi, I would gladly receive some feedback on my pull request.

1. Are you interested in adding a GitLab report format to DependencyCheck?
2. Do you agree the best way to implement it is by adding a template and a new report format?
3. Do you have any pointers on (some of) the missing fields?
4. Do you think it's still a good idea to merge this even if some fields of the target format are not available right now?
5. Would you accept pull requests adding the additionally needed information to the template engine's context?

2023-09-04 22:57 UTC, aikebah reviewed
Some preliminary feedback. Based on the various comments you already put in I think it needs some further investigation into resolving the various issues with the GitLab report format versus the information we currently have available to make it so mature that I would vote for inclusion.

Nevertheless I'm in favor of the initiative, and even if we can't reach to an acceptable level of support the efforts to try and achieve as much as reasonbly possible are useful for anyone wanting to embed DependencyCheck into GitLab dependency-scanning. 

If not as a formally supported format people could always use a partially completed and syntactically working template as their own report format (using the VSL as a custom-format report - see https://github.com/jeremylong/DependencyCheck/issues/5824#issuecomment-1632834729 for some details on that approach)

2023-09-04 22:57 UTC, aikebah commented on core/src/main/resources/templates/gitlabReport.vsl
> +                        ## "links": [], --> not implemented
This would be the proper place to put the references that you coded in the identifiers

2023-09-04 22:57 UTC, aikebah commented on core/src/main/resources/templates/gitlabReport.vsl
> +                        "solution": "" ## todo: not in our dataset?
Solution indeed not available in our dataset; in most cases solution would be 'update to patched version', but cases may exist every now and then where a vulnerability is valid 'for all current versions' as there is either no fix yet, or e.g. the maintainer refuses to change the code to 'secure by default' and only indicates that their library is not intended to be used with untrusted data.. 
However I think the format spec allows to leave this property completely out:
```json
        "required": [
          "id",
          "identifiers",
          "location"
        ],
```
So not sure why you think it would have to be included to be compliant with the spec
only id, identifiers and location are required in the vulnerabilities array items

2023-09-04 22:57 UTC, aikebah commented on core/src/main/resources/templates/gitlabReport.vsl
> +    ],
In my view for this case we should do a better job if we claim to support the GitLab dependency_scanner reporting, rather than blindly lie that we obtained all the dependency information from a maven pom.xml.

2023-09-04 22:57 UTC, aikebah commented on core/src/main/resources/templates/gitlabReport.vsl
> +                                #if( $foreach.hasNext ),#end
This code should move to the 'links' section. The identifiers list would hold the information similar to what's in the vulnerability section header in the HTML report:
https://github.com/jeremylong/DependencyCheck/blob/3871517289d2cb0cf2c75cbe6ec229d280da8b8d/core/src/main/resources/templates/htmlReport.vsl#L993-L999

2023-10-08 11:57 UTC, jeremylong requested changes
Please see the comments from @aikebah.

2023-10-10 07:02 UTC, niklasfi commented on core/src/main/resources/templates/gitlabReport.vsl
> +                        ## "links": [], --> not implemented
yup, moved it there

2023-10-10 07:05 UTC, niklasfi commented on core/src/main/resources/templates/gitlabReport.vsl
> +                        "solution": "" ## todo: not in our dataset?
sorry, this was an oversight. You are right, that it is optional, and as such, I've commented it out for now.

2023-10-10 07:06 UTC, niklasfi commented on core/src/main/resources/templates/gitlabReport.vsl
> +                                #if( $foreach.hasNext ),#end
updated in latest commit

2023-10-10 07:09 UTC, niklasfi commented
hi @jeremylong @aikebah sorry for taking so long to respond to your well thought out remarks on the pull request. I have implemented the changes as you suggested except for the `dependency_files` section. There I don't really know how to best proceed.

2023-10-14 11:15 UTC, jeremylong commented
@niklasfi thanks! Supporting this format shows that we might be missing a field on the dependency object: `source`. Where the source would be something like: `pom.xml`, `poetry.lock`, `path/to/some.jar`. We could then add dependencies to the array grouped on source. I think this information would be useful for other reasons as well. I'll file an enhancement request.

2023-11-09 10:59 UTC, niklasfi commented
fyi we have set up a fork of this project in our private gitlab and are now using the generated SNAPSHOT builds in our piples. I can report it's working as is, with the known restrictions (source file is kind of a lie). In the process of setting this up, I found a couple more bugs. That is where the extra commits come from.

2023-11-18 19:26 UTC, jeremylong commented
Sorry for the delays - I will include this in the 9.0.0 release.

2023-11-21 11:15 UTC, jeremylong commented on core/src/main/resources/templates/gitlabReport.vsl
> +    ],
@aikebah I agree - but I think I'm going to merge this one and then fix it once we have better source information (see #5989).

2023-11-21 11:16 UTC, jeremylong approved these changes

2023-11-21 11:18 UTC, merged