fix: check valid for hours for NVD API
dependency-check/DependencyCheck pull request #6225
Opened 2023-12-05 11:42 UTC by jeremylong

resolves #6222

2023-12-05 13:59 UTC, strangelookingnerd requested changes

2023-12-05 13:59 UTC, strangelookingnerd commented on core/src/main/java/org/owasp/dependencycheck/data/update/NvdApiDataSource.java
>                  LOGGER.info("Skipping the NVD API Update as it was completed within the last 30 minutes");
@jeremylong Isn't the log output misleading here? It should not say 30 minutes, should it?

2023-12-05 23:33 UTC, jeremylong commented on core/src/main/java/org/owasp/dependencycheck/data/update/NvdApiDataSource.java
>                  LOGGER.info("Skipping the NVD API Update as it was completed within the last 30 minutes");
```suggestion
                LOGGER.info("Skipping the NVD API Update as it was completed within the last {} minutes", validForSeconds/60);
```

2023-12-05 23:34 UTC, jeremylong commented on core/src/main/java/org/owasp/dependencycheck/data/update/NvdApiDataSource.java
>                  LOGGER.info("Skipping the NVD API Update as it was completed within the last 30 minutes");
thanks for pointing this out!

2023-12-06 06:44 UTC, strangelookingnerd approved these changes

2023-12-06 08:22 UTC, strangelookingnerd approved these changes

2023-12-06 10:17 UTC, merged