false positives for jetcd libraries
dependency-check/DependencyCheck pull request #7117
Opened 2024-10-30 13:41 UTC by joannakotula

## Fixes Issue 

## Description of Change

* jetcd libraries (core, api, grpc) were treated as etcd server (similar to issue #6981)
* jetcd-grpc was treated as io.grpc library (which it includes)

## Have test cases been added to cover the new functionality?

no

2024-10-30 14:40 UTC, joannakotula commented
I see that some checks failed in codacy but I cannot see the details. Please advise.

2024-11-01 03:16 UTC, chadlwilson commented on generatedSuppressions.xml
> +   <cpe>cpe:2.3:a:redhat:etcd:0.8.3:*:*:*:*:*:*:* </cpe>
```suggestion
   <cpe>cpe:/a:etcd:etcd</cpe>
```

2024-11-01 03:16 UTC, chadlwilson commented on generatedSuppressions.xml
> +   <cpe>cpe:/a:grpc:grpc</cpe>
```suggestion
   <cpe>cpe:/a:etcd:etcd</cpe>
   <cpe>cpe:/a:grpc:grpc</cpe>
```

2024-11-01 03:16 UTC, chadlwilson commented on generatedSuppressions.xml
> +   file name: jetcd-core-* - not an etcd server
```suggestion
   FP per issue #7123
```

2024-11-01 03:16 UTC, chadlwilson commented on generatedSuppressions.xml
> +   file name: jetcd-grpc-* - not an etcd server, not a grpc library (includes one though)
```suggestion
   FP per issue #7123
```

2024-11-01 03:18 UTC, chadlwilson commented on generatedSuppressions.xml
> +   <cpe>cpe:2.3:a:redhat:etcd:0.8.3:*:*:*:*:*:*:* </cpe>
If `redhat:etcd` is needed, might need to include it in standard format consistent with the others, rather than a version-specific expression.

2024-11-01 03:18 UTC, chadlwilson commented on generatedSuppressions.xml
> +   <cpe>cpe:/a:grpc:grpc</cpe>
If `redhat:etcd` is needed, might need to include it in standard format consistent with the others, rather than a version-specific expression.

2024-11-04 12:20 UTC, joannakotula commented on generatedSuppressions.xml
> +   file name: jetcd-core-* - not an etcd server
Changed

2024-11-04 12:21 UTC, joannakotula commented on generatedSuppressions.xml
> +   file name: jetcd-grpc-* - not an etcd server, not a grpc library (includes one though)
Changed

2024-11-04 12:21 UTC, joannakotula commented on generatedSuppressions.xml
> +   <cpe>cpe:/a:grpc:grpc</cpe>
Removed version, please check if it is correct

2024-11-04 12:51 UTC, chadlwilson requested changes

2024-11-04 12:51 UTC, chadlwilson commented on generatedSuppressions.xml
> +   <cpe>cpe:2.3:a:redhat:etcd</cpe>
```suggestion
   <cpe>cpe:/a:redhat:etcd</cpe>
```

2024-11-04 12:51 UTC, chadlwilson commented on generatedSuppressions.xml
> +   <cpe>cpe:2.3:a:redhat:etcd</cpe>
This is "URI binding representation" CPE format, which is version agnostic. Not sure if both work, but better to be consistent.

2024-11-04 12:51 UTC, chadlwilson commented on generatedSuppressions.xml
> +   <cpe>cpe:2.3:a:redhat:etcd</cpe>
```suggestion
   <cpe>cpe:/a:redhat:etcd</cpe>
```

2024-11-04 19:25 UTC, joannakotula commented on generatedSuppressions.xml
> +   <cpe>cpe:2.3:a:redhat:etcd</cpe>
done

2024-11-04 19:25 UTC, joannakotula commented on generatedSuppressions.xml
> +   <cpe>cpe:2.3:a:redhat:etcd</cpe>
done

2024-11-04 22:51 UTC, chadlwilson approved these changes

2024-11-06 08:53 UTC, joannakotula commented
I've missed the `jetcd-common` library :facepalm: 
I don't know the project very well, but maybe I can suppress all jetcd-x libraries by something like:
```xml
<suppress>
   <notes><![CDATA[
   FP per issue #7123
   ]]></notes>
   <packageUrl regex="true">^pkg:maven/io\.etcd/jetcd-[a-z]*@.*$</packageUrl>
   <cpe>cpe:/a:etcd:etcd</cpe>
   <cpe>cpe:/a:redhat:etcd</cpe>
</suppress>
```
:question:

2024-11-06 12:48 UTC, chadlwilson commented
Yeah, if you look at the rest of the suppressions file you'll note that there a number of suppressions like that.

2024-11-06 14:01 UTC, joannakotula commented
Ok, so from my point of view, the PR is ready :wink: 
I'd still like to understand why the checks failed - the log message says only "An error occurred during this step."
When can I expect the merge?

2024-11-06 14:03 UTC, jeremylong approved these changes
LGTM

2024-11-06 14:03 UTC, merged

2024-11-06 14:04 UTC, jeremylong commented
Super busy - but I expect to release the next version within a few days.

2024-11-06 14:05 UTC, jeremylong commented
regarding the failed check - I really dislike how frequently that check fails. It really hasn't been valuable and I'm considering removing the codacy check from the workflow soon.