Added some caching for CveDB in order to speedup some scans
dependency-check/DependencyCheck pull request #744
Opened 2017-05-24 07:43 UTC by v6ak

## Fixes Issue #

Some items (e.g., Linux kernel) have many CVE entries, which takes much time to load it. When such CPE is matched for multiple dependencies, the scan takes much time and can easily hit the 10 minutes limit.

## Description of Change

Result of getVulnerabilities(String cpeStr) is cached under a soft reference. Other parts of CveDB are prepared for caching.

## Have test cases been added to cover the new functionality?

*no*

There is no new functionality, it is just enhancement of the old functionality. I've thought about tests, but it should just improve performance and I am not sure if it is appropriate to test it in unit/integration tests.

2017-05-24 07:43 UTC, jeremylong commented
Can one of the admins verify this patch?

2017-05-24 12:41 UTC, jeremylong requested changes
Overall I like the change! Couple of minor changes requested (see review comments) and the one question on the synchronization of the map.  All of the methods are synchronized, so that might be overkill - but I'm all for safety rather then creating weird un-reproducible bugs.

2017-05-24 12:41 UTC, jeremylong commented on dependency-check-core/src/main/java/org/owasp/dependencycheck/data/nvdcve/CveDB.java
> +    private final Map<String, List<Vulnerability>> vulnerabilitiesForCpeCache = new ReferenceMap(HARD, SOFT);
dependency-check, for the most part, is multi-threaded. While the `getVulnerabilities()` method is synchronized - it might be safer to use [`Collections.synchronizedMap(java.util.Map)`](http://docs.oracle.com/javase/7/docs/api/java/util/Collections.html?is-external=true#synchronizedMap(java.util.Map)).  Thoughts?

2017-05-24 12:41 UTC, jeremylong commented on dependency-check-core/src/main/java/org/owasp/dependencycheck/data/nvdcve/CveDB.java
> +        clearCache();
No need to clear the cache here. The saving of properties to the DB would have no affect on the vulnerabilities.

2017-05-24 12:41 UTC, jeremylong commented on dependency-check-core/src/main/java/org/owasp/dependencycheck/data/nvdcve/CveDB.java
> +        clearCache();
For performance reasons, it would be better if this `clearCache()` was moved down 5 lines next to the `instance.usageCount = 0;`. As 'close()' may be called by multiple threads - another thread may still need to get vulnerabilities.

2017-05-24 13:46 UTC, v6ak commented on dependency-check-core/src/main/java/org/owasp/dependencycheck/data/nvdcve/CveDB.java
> +        clearCache();
Good point, I have missed that.

2017-05-24 13:48 UTC, v6ak commented on dependency-check-core/src/main/java/org/owasp/dependencycheck/data/nvdcve/CveDB.java
> +    private final Map<String, List<Vulnerability>> vulnerabilitiesForCpeCache = new ReferenceMap(HARD, SOFT);
IMHO it is not needed, but I'll change it if it helps to fit better in your culture.

2017-05-24 13:54 UTC, v6ak commented on dependency-check-core/src/main/java/org/owasp/dependencycheck/data/nvdcve/CveDB.java
> +        clearCache();
This is true, at least at this moment, but I believe:

1. This line helps maintainability. The logic behind is that one write clears everything from cache. We could break it in multiple parts and have, say, clearVulnerabilityCache and similar methods, but I see it as overkill at the moment. Also, one would have to be careful about cross-dependencies over multiple table (e.g., when adding a property that influences how are vulnerabilities read).
2. It does not hurt performance in typical usage.

2017-05-26 11:37 UTC, jeremylong approved these changes

2017-05-26 11:37 UTC, merged

2017-05-26 11:38 UTC, jeremylong commented
Thanks for the PR!